name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt
    - name: build
      run: cp config.py.example config.py && ./compile.py
    - name: run
      run: chown -R nobody:nogroup . && su nobody -s /bin/bash -c ./run.py
    - name: basic test
      run: wget http://localhost:9090 -O /dev/null && kill $(cat twistd.pid)
